name: Simple Workflow

# Define cu치ndo debe ejecutarse el workflow
on:
  push:
    branches:
      - main  # Se ejecuta cuando hay un push en la rama "main"
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

# Definimos los jobs que queremos ejecutar
jobs:
  example-job:
    runs-on: ubuntu-latest  # El job se ejecuta en una m치quina con Ubuntu
    
    # Los steps son los pasos que el job ejecutar치
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clona el repositorio en la m치quina virtual

      - name: Say hello
        run: echo "Hello, world!"  # Muestra un mensaje simple

      - name: List files
        run: ls -l  # Lista los archivos del repositorio

      - name: Print current date
        run: date  # Imprime la fecha actual
